### ISSUE TITLE
make clean does not clean everything

### ISSUE THREAD

**Issue by rhertzog** [vanhauser-thc/AFLplusplus#158]
When I tried to update the Debian package, I got multiple errors from dpkg-source due to the following binaries being present after a make clean:
- gcc_plugin/.test2
- llvm_mode/.test2
- .test
- .test1
- .test2

Those are created by `$(shell ...)` invocations in the makefile. IMO you should really switch to proper autoconf support because doing such tests directly in the makefile is rather ugly and creates problems such as this one.

**Comment by vanhauser-thc** [comment]
it is correct that gcc_plugin/.test2 was forgotten, however the others are deleted.
can you please recheck?

**Comment by rhertzog** [comment]
I'm pretty sure that I had to remove more than just gcc_plugin/.test2. But it's true that they are removed by "make clean".

That said the Debian build infrastructure is complex and tries to look up in the Makefile the available targets with some "make -s -n" invocations and that's most likely what is recreating those files after they have been removed in some way.

Such a make invocation should not have any side effect and your usage of `$(shell)` has such unintended side effects. Thus I believe you should reconsider your approach here.

**Comment by vanhauser-thc** [comment]
Because of the autodetect features in the Makefile we get very little issues about "cant get it compiled" etc. - which is a huge relief ... in other repositories I have there is less magic and much more issues being created. So I doubt me or one of the other maintainers see an advantage in implementing a new approach - it would take a long time to get right and then likely result in people opening issues ....

So the easier approach is rather - we ensure that the .test files are ensured to be removed :)
I will have another look at the Makefiles and see what I can tweak. when I am done I comment here and you can see if it's working then.

**Comment by vanhauser-thc** [comment]
ok that was actually fast to do. .test* files should now never be found unless control-c is pressed during a make. and make clean will clean them too.

if you still find files, please report.

**Comment by vanhauser-thc** [comment]
is this fixed for you and can this be closed?

off-topic: I saw your patch in Debian for libdislocator/Makefile - I incorporated this and then saw that the same issue is in libtokencap/Makefile (and fixed it there too, you might want to do the same). That will be in the 2.61c release - whenever that is.

**Comment by rhertzog** [comment]
I have not tested the git version yet but given that the file is removed directly in the `$(shell)` invocation it's probably good enough. Thanks for merging my other changes.

BTW it would be nice if you provided some way to achieve what we do with this patch:
https://salsa.debian.org/pkg-security-team/aflplusplus/blob/debian/master/debian/patches/hardcode-clang-and-LLVM-version-for-build-and-runtime.patch

**Comment by devnexen** [comment]
a bit off topic but surprised by the change here https://salsa.debian.org/pkg-security-team/aflplusplus/blob/debian/master/debian/patches/hardcode-clang-and-LLVM-version-for-build-and-runtime.patch#L29

**Comment by rhertzog** [comment]
@devnexen Yeah, that change is not required for us since it only applies to OpenBSD kernels, but I wanted to be consistent and replace all invocations of llvm-config with the version we use. There's no Debian/OpenBSD that I know but we do have a Debian/kFreeBSD port so who knows? :)

**Comment by vanhauser-thc** [comment]
> I have not tested the git version yet but given that the file is removed directly in the `$(shell)` invocation it's probably good enough. Thanks for merging my other changes.
> 
> BTW it would be nice if you provided some way to achieve what we do with this patch:
> https://salsa.debian.org/pkg-security-team/aflplusplus/blob/debian/master/debian/patches/hardcode-clang-and-LLVM-version-for-build-and-runtime.patch

for the Makefile that would easily be just a CC=clang-9 CXX=clang++-9 LLVM_CONFIG=llvm-config-9 when calling make, and I made a change to honor LLVM_CONFIG when running test.sh 

but for afl-clang-fast ... dunno. We *could* set it fixed via Makefile -D llvm-config bin magic. llvm_mode would need to be recompiled and installed anyway if someone installs clang-10 and wants to use it (because of the afl llvm shared libraries).

is that what you think would be good?

@hexcoder- / @andreafioraldi  ?

**Comment by rhertzog** [comment]
> is that what you think would be good?

Yeah, having the Makefile set some "define" via `$(CC) -D` and respect those in the source code looks like a viable approach.

I'm fine with overriding CC/CXX/LLVM_CONFIG for the Makefile, but should that be done only for the llvm_mode directory? What happens if other directories are compiled with clang instead of gcc?

**Comment by vanhauser-thc** [comment]
You would only need to set LLVM_CONFIG, only the llvm_mode/Makefile (and test.sh script) look for it, all others ignore it.

I put that on the TODO, I think its done this week.

**Comment by vanhauser-thc** [comment]
@rhertzog  haha ... just looked at the code - and its already in there ;)

Makefile: LLVM_BINDIR=$(shell $(LLVM_CONFIG) --bindir)

alf-clang-fast.c: main() -> edit_params():
```
  has_llvm_config = (strlen(LLVM_BINDIR) > 0);

  if (!strcmp(name, "afl-clang-fast++")) {

    u8* alt_cxx = getenv("AFL_CXX");
    if (has_llvm_config)
      snprintf(llvm_fullpath, sizeof(llvm_fullpath), "%s/clang++", LLVM_BINDIR);
```
you just have to set LLVM_CONFIG=llvm-config-9 when compiling afl++ and thats it :)
