### ISSUE TITLE
gcc_plugin built with GCC 9.2.1 does not pass tests

### ISSUE THREAD

**Issue by elklepo** [vanhauser-thc/AFLplusplus#175]
I've used Dockerfile to build AFLPlusPlus with all plugins and unfortunately, `gcc_plugin` fails tests performed during `make tests`:
```
...
[!] gcc_plugin instrumentation produces a weird number of instrumented locations: 7
...
```
Version of gcc installed in docker image is:
```
gcc-9 (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
```

**Comment by vanhauser-thc** [comment]
well this is the wrong repo - it is gcc that sucks :)
seriously, llvm_mode is so much better.
we dropped gcc_plugin for the moment because their instrumentation is not good, maybe in gcc10 it gets better. we only leave it in because if code does not compile with clang and someone wants to use the whitelist feature ...

**Comment by elklepo** [comment]
Oh, great, thanks for help! I'll use llvm_mode then. :)
