### ISSUE TITLE
build_qemu_support.sh fails on ArchLinux cause of capstone.h location

### ISSUE THREAD

**Issue by fuzzah** [vanhauser-thc/AFLplusplus#201]
Hello.

In this file of downloaded qemu source:
`qemu-3.1.1/include/disas/capstone.h`

capstone.h is included as
`#include <capstone.h>`

Running ./build_qemu_support.sh fails on ArchLinux, however it works when i change `#include` as follows:
`#include <capstone/capstone.h>`

Also, is there some preferred distro to use for fuzzing with AFL++? I installed Arch because it provides modern releases of every single package - including llvm, clang, gcc - out of the box.

**Comment by vanhauser-thc** [comment]
That is a difference between older and newer versions of capstone. 
It is actually a problem with qemu and your system as it is something we did not touch.
If the one installed in the system is new, then the build fails (because the qemu version is old - newer qemu version underperform so we dont upgrade).

The only sensible fix I see is to checkout capstone on our own and either patch qemu to use the new include path (and what else changed) or checking out an older version (and ensure that the git pull that is performed in qemu's configure script does not void that).

@andreafioraldi ?

**Comment by fuzzah** [comment]
Capstone version I have is 4.0.1-3 (as reported by `pacman -Qi capstone`)

**Comment by vanhauser-thc** [comment]
@fuzzah I made a simple change - does it work now for you?

@andreafioraldi I am not happy with my solution. it is easy and quick, but the internal capstone version is 3.0.5-rc3. Having 3.0.5 would be better (or even 4.0.1) but that means downloading,
overwriting the existing capstone directory, etc. and I would not want to make such a big change in your domain :)

**Comment by fuzzah** [comment]
@vanhauser-thc , yes, now it compiles normally. Thanks!

**Comment by vanhauser-thc** [comment]
@andreafioraldi do you want to keep the issue open and get a newer capstone version? (I can also take care of this if you are busy with other stuff.) Or are you fine with 3.0.5-rc3?

**Comment by andreafioraldi** [comment]
If your fix works, I'll not touch it. We don't need to update capstone, it is used for debugging not when lifting (our use case). QEMU would hardly benefit from new capstone features.
