### ISSUE TITLE
[Suggestion] Some advice for creating a better commit history

### ISSUE THREAD

**Issue by bruce30262** [vanhauser-thc/AFLplusplus#215]
This issue is more like a suggestion/discussion thread for creating a better code commit history in AFL++.  

When I saw the discussions in #214 and start browsing the commit history in AFL++, I found the commit history kind of messy. Some of the commit message aren't clear enough to provide the information of the code modification ( for example fc77f0bb969b0d6f2add 😅 ). Also I believe some of the commits can be squashed into one single commit ( for example 20b8fc075bb9b and 713952b9c7bae59408), which will make the commit history more simple and clear to read.  

Commit such as 3549cbb3a27ca46d81f47 is a nice commit message example. Also please consider open a new branch for bugfix/new feature and squash + merge the commit back to the master branch instead of doing all the things on master branch. 

Again not to brag about my software developing experience, but for a better experience of developing/contributing the project, it would be nice if the project has a better code commit history ( It's kind of painful to watch @wideglide spending tons of hours walking through bunch of commits just to find the root cause...  ).

**Comment by hexcoder-** [comment]
Yes, it is not ideal this way, but i think the committers are aware of that. The priority of this point compared to fixing bugs is of course pretty low, so only when we do easy changes we have the inclination to think about a nice reading experience and optimized commits. Otherwise it is just too hard to commit in an optimal fashion. Thats life, i guess.

**Comment by vanhauser-thc** [comment]
I am calling myself a security professional or hacker - not a developer, hence my development skills are rather limited ... On the other hand I handle projects with quite some users (hydra, thc-ipv6, afl++) so better code quality, testing, commits, etc. is a pretty good thing to have/do ;-)
I would say I am getting there slowly ... test framework is there, travis integration, code formatting ... weak point are the commits itself (numbers, description, etc.) as I often work on the master directly instead of creating a branch  - simply because of the large overhead.
fc77f0b, 20b8fc0 and 713952b were because I wanted and had to be in bed for 2 hours already however wanted to get that fix out that was breaking afl-fuzz, and getting that right took 100% of my last 20% of mental resources ;)
I will try to do better :)

**Comment by bruce30262** [comment]
@hexcoder- @vanhauser-thc thanks for replying ! Here are some of my thoughts about the topic you've mentioned in the reply:

I agree bug fixing is more important than this. However I think it's not that hard to re-organize the local commits before pushing them to the remote github repo -- a few `git rebase -i` command should do the trick. I wouldn't mind waiting for a few more minutes/hours ( even days! ) to see the code appears on the master branch in the github repo with a nice commit message :) But again I'm not the one developing, so I have no idea how complex the commit code would be, maybe it would be a PITA to organize those commits, I don't know :P  

What I want to say is it would be really nice to have a clear commit history ( like [pwntools](https://github.com/Gallopsled/pwntools/commits/dev) ) in the future ( for the commit so far just leave it, I don't want to organize that either 😅 ). It'll benefit guys like me ( who isn't familiar with the code in AFL++ ) have a better understanding about the code ( e.g. how those code effect XXX part of the fuzzer ). Also it'll make bug locating lot more easier, since those commits directly told us which part of the code did they modified.   

P.S. Feel free to close this issue anytime you feel like it, it's just a suggestion after all :)

**Comment by domenukk** [comment]
I think we will try to keep the history a wee bit tidier from now on.
Thanks for the ping, definitely true :)
Closing this issue.
