### ISSUE TITLE
qemu_mode crash

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#24]
this crash in qemu only seem to happen with specific input files. weird.

```
afl-fuzz -Q -i in -o out -- ./xmllint @@
```

always after exactly 5 seconds of running:
```
[-] PROGRAM ABORT : Unable to communicate with fork server (OOM?)
         Location : run_target(), afl-fuzz.c:2718
```

to reproduce:
```
wget ftp://xmlsoft.org/libxml2/libxml2-2.9.2.tar.gz
tar xzf ibxml2-2.9.2.tar.gz
cd ibxml2-2.9.2
./configure --disable-shared
make
mkdir in
cp ./test/schemas/complex-type-extension_0.xml in/
```
I tried a few other test xml files but they did not produce a crash

@andreafioraldi - thats more your competence, can you have a look?

**Comment by andreafioraldi** [comment]
mmmm this is a problem that affects also afl 2.52b with QEMU 2.1.0.
Instead of aborting with `Unable to communicate with fork server (OOM?)` it gets stuck without updating the status screen.

In the worst case, there is a bug in the code that compiles blocks when requested in the parent process. 

Note that with `-d` it seems to work.

**Comment by andreafioraldi** [comment]
Ok I have disabled TCG block caching in the parent and the problem is not present now, we are in the worst case I think. This will be very hard to debug.

**Comment by andreafioraldi** [comment]
Update: disabling TCG block chaining the bug disappear so the afl 2.52b bug is different and not present in afl++.

**Comment by andreafioraldi** [comment]
The crash is in tb_gen_code when called from afl_wait_tsl. I'm starting to think that this is a QEMU 3.1.0 bug.

**Comment by andreafioraldi** [comment]
OK, I fixed it. This deserves a brief explanation because it has always been a bug in afl qemu_mode.
The problem is that some software create pages of code after the main() like jit compilers or dlopened libraries (when using AFL_INST_LIBS) and then request the translation for caching to the parent process that has not mapped this pages.
The bug does not appear disabling chaining xmllint only by change but it is not related to chaining.
The fix is simple, I check in the parent process if the PC of the requested block is valid memory.
IDK what xmllint does but at some point requests the translation of not mapped memory in the parent.

**Comment by andreafioraldi** [comment]
@vanhauser-thc can you double check the fix testing on xmllint?

**Comment by andreafioraldi** [comment]
![Screenshot at 2019-07-20 13-22-45](https://user-images.githubusercontent.com/16168186/61578080-7ea39200-aaf1-11e9-83e8-926c6df05c75.png)

Now v8js can be fuzzed in QEMU mode at a shitty speed but it works.

**Comment by vanhauser-thc** [comment]
@andreafioraldi - sorry took me long. doesnt crash anymore, great job!
