### ISSUE TITLE
how to calculate total paths

### ISSUE THREAD

**Issue by lc11007** [vanhauser-thc/AFLplusplus#37]
hello,I use the afl-fuzz to fuzz my code.I find something about the total paths.
My code:
int main(int argc, char *argv[])
{
    int a = 0;
    int b = 0;
    int c = 0;
    std::ifstream fin;
    std::string file_name(argv[1]);
    fin.open(file_name);
    std::string str;
    getline(fin, str, ' ');
    a = stoi(str);
    getline(fin, str, ' ');
    b = stoi(str);
    getline(fin, str, ' ');
    c = stoi(str);

    std::cout<<a << b << c<<std::endl;

     if(a>b)
    {
        printf("a>b::a%d\n", a);
    }
    else 
    {
        printf("a>b::b%d\n", b);
    }

    if(a>c)
    {
        printf("a>c::a%d\n", a);
    }
    else 
    {
        printf("a>c::c%d\n", c);
    }

    return 0;
} 

Then, I get the total paths is 5,but I think the total paths is 4.Can you have some suggestion to me? Thanks.

**Comment by vanhauser-thc** [comment]
the open call can fail if empty or invalid, that would be another case. also I dont know what happens if not enough data is in the input file.

but you can find out yourself: in the -o out directory is a subdirectory called queue/ which contains 5 entries, one for each path detected. just ran them with your file and you will see the 5 different paths it did find.

**Comment by lc11007** [comment]
yes,I see the 5 entries.they are 
(1) 3 2 4
(2) 2 3 1
(3) 2 3 4
(4) 3 2 1
(5)3..V....r..t@t..
then , I use my code to run them.but I only get the 4 different paths.so,I think the computation of total paths is a special calculation method.I hope to know the special method,it is important for me.Thanks.
