### ISSUE TITLE
Floating point laf-intel

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#56]
Currently, the laf-intel LLVM pass seems to not support the split
of floating point comparisons (`CmpInst::FCMP_*`). RIght?

I will implement also a QEMU CompareCoverage extension for x86 floating point comparisons (https://docs.oracle.com/cd/E19120-01/open.solaris/817-5477/epmnp/index.html).

**Comment by hexcoder-** [comment]
Correct, the original author did not support it. I left it this way.
If we extend it to floating point, we should make sure that QEMU and llvm_mode do the same thing (split to byte compares, I assume) so that the behaviour is comparable.

**Comment by hexcoder-** [comment]
Lets have some demo code. How about this?
```
#include <stdio.h>
#include <stdlib.h>

int main(void)
{
	float a;
	double b;
	long double c;

	if (3 > scanf("%f %lf %Lf", &a, &b, &c)) {
		fprintf(stderr, "error: expected 3 floating point values, aborting\n");
		return 1;
	}

	if (a == 42.5) {
		if (b == 43.5) {
			if (c == 44.5) {
				abort();
			}
		}
	}
	return 0;
}

```

**Comment by hexcoder-** [comment]
I have now done a first realization along the lines of laf-intel's split compares (https://github.com/vanhauser-thc/AFLplusplus/commit/1e503a586d9f3d45e27bc1dbb3b2093c1e5f7b6f). I am open for feedback.
Tests from big endian machines would be welcome.

**Comment by andreafioraldi** [comment]
I'm trying the demo, how much time should take to trigger the abort?

**Comment by hexcoder-** [comment]
The demo takes too long (live is too short).

This will trigger in 4 seconds with given input "\n"
```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int main(void)
{
        float a;
        double b;
        long double c;

        ssize_t got;
        if (sizeof(float) < (got = read(STDIN_FILENO, &a, sizeof(float)))) {
                fprintf(stderr, "error: expected %lu bytes, got %ld aborting\n", sizeof(float), got);
                return 1;
        }
        if (sizeof(double) < (got = read(STDIN_FILENO, &b, sizeof(double)))) {
                fprintf(stderr, "error: expected %lu bytes, got %ld aborting\n", sizeof(double), got);
                return 1;
        }
        if (sizeof(long double) < (got = read(STDIN_FILENO, &c, sizeof(long double)))) {
                fprintf(stderr, "error: expected %lu bytes, got %ld aborting\n", sizeof(long double), got);
                return 1;
        }

        if (a == 42.5) {
                abort(); /* four seconds in default mode */
                if (b == 43.5) {
                        abort();
                        if (c == 44.5) {
                                abort();
                        }
                }
        }
        return 0;
}

```
Next step would be to comment out the first abort and test that, but a double is more difficult to match.
And after that comment out the second abort()...

**Comment by andreafioraldi** [comment]
I tested also with a and b as floats and doesn't trigger the second abort. We should rethink something. Describe in details how you split floats in a mail, I have some ideas.

**Comment by andreafioraldi** [comment]
Hi Heiko,
I'm reading your code for floats.
Instead of inserting a branch to compare the exponent, why don't normalize
the two floats to the same exponent (the max or the min of the two). Then
compare the mantissa with a splitted integer comparison.
My plan in QEMU is to insert an helper that returns the normalized pair of
floats and then apply the Compare Coverage to only the sign and then to the
mantissa.

Andrea.

**Comment by andreafioraldi** [comment]
I'm not understanding the produced code in IDA. The highlighted if causes the abort when evaluates to true:
![Screenshot at 2019-10-02 10-01-41](https://user-images.githubusercontent.com/16168186/66027741-d308bc00-e4fb-11e9-9706-04207022a627.png)
As you can see from the xrefs v161 is never 1 and also v168.

**Comment by andreafioraldi** [comment]
I attach the code, the binary and the IDB.
[aaa.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3680047/aaa.tar.gz)

**Comment by vanhauser-thc** [comment]
@andreafioraldi I doubt Heiko has IDA.

my recommendation: verify the pseudo code with Ghidra. IDA sometimes decompiles to wrong code.

**Comment by hexcoder-** [comment]
Hi Andrea,

normalizing is a problematic term, because floats are already normalized
(unless values are at the extreme edge of the range).
Adjusting the exponent on one of them to equal the other one can cause
loss of precision when mantissa bits are shifted out thus affecting the
comparison result.
And I think it might be slower compared to extracting and comparing exponents,
because the chain of tests can be shortcut.

My algorithm is currently like that:

  1.  First pass: Simplify comparisons >= and <= into separate > and == comparisons
(as it is done for the integer case)

  1.  Second pass: Isolate signs and integer-compare them
  2.  Isolate exponents and integer-compare them

(integers are chosen with a width of 8, 16 or 32 bit in order to use

the already present integer split compare from laf-intel)

  1.  Isolate mantissas and integer-compare them

(integers are chosen with a width of 8, 16 or 32 bit in order to use

the already present integer split compare from laf-intel)

  1.  Third pass: Let the laf-intel integer splitting take place.

I don’t know if this is optimal, but it should be correct
(unless values like Infinity and notAnumber are used).

I wonder if simply splitting float comparisons at byte boundaries would work.
It should for == comparisons, but not for < and >.

This answer is from work, at home I have some more test programs.

Heiko
Von: Andrea Fioraldi <notifications@github.com>
Gesendet: Mittwoch, 2. Oktober 2019 09:48
An: vanhauser-thc/AFLplusplus <AFLplusplus@noreply.github.com>
Cc: hexcoder <heiko@hexco.de>; Assign <assign@noreply.github.com>
Betreff: Re: [vanhauser-thc/AFLplusplus] Floating point laf-intel (#56)

Hi Heiko,
I'm reading your code for floats.
Instead of inserting a branch to compare the exponent, why don't normalize
the two floats to the same exponent (the max or the min of the two). Then
compare the mantissa with a splitted integer comparison.
My plan in QEMU is to insert an helper that returns the normalized pair of
floats and then apply the Compare Coverage to only the sign and then to the
mantissa.

Andrea.

**Comment by hexcoder-** [comment]
@andreafioraldi, yes vanhauser-thc is right, I don't have it (too expensive for a hobbyist).
Usually I look at the output of
afl-clang-fast -S -emit-llvm ...
or 
afl-clang-fast -S ...

But I also tried to fuzz the first two FP comparisons in a row since 15 hours without any luck. I nearly instantly have a total of 15 paths, and thats it, no more progress :-(.

If I verify the abort case manually (giving binary floats of 42.5 and 43.5 on stdin), I can see the comparisons are triggered correctly.

Fuzzer is still guessing too erratically, I guess...

**Comment by andreafioraldi** [comment]
This is my point, very strange, check if the mantissa is correctly splitted into byte-level comparisons.

**Comment by andreafioraldi** [comment]
I attach the disassembled and the decompiled code from IDA if you need it.
My laptop is Java free and I don't use Ghidra but I often use radare2 (as you may have noted in previous mails).
[ida_output.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3681398/ida_output.tar.gz)

**Comment by hexcoder-** [comment]
Here are my assembly files for instrumented a.c from above:
[instrumented_assembly.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3681468/instrumented_assembly.tar.gz)
Works as expected.

**Comment by hexcoder-** [comment]
ok, error is confirmed.
Uninstrumented and instrumented programs differ in behaviour for == 
comparison for type double.

Will see into that...

**Comment by hexcoder-** [comment]
Error is analyzed and fixed b5c2646360a58baf00dcb1788833aa0b5a9117ce. Treatment of mantissa part was wrong, because my masks were not created correctly.

**Comment by andreafioraldi** [comment]
Good job! I will test it tomorrow evening

**Comment by andreafioraldi** [comment]
The compiled program now behaves correctly but I am still unable to crash the example.
One comparison is bypassed in few seconds but I cannot crash two nested comparisons.
Maybe there is a bug in the BB placement? @hexcoder- , have you the same problem with the example?

**Comment by hexcoder-** [comment]
It really depends on the input. When I supply an input with three values slightly off (say +/-2), afl-fuzz triggered three nested comparisons in about 15 seconds. The crashing input was correct in this case.
So, I deduce the BB placement is correct.

However when I start with something like "\n", the path discovery stalls typically after reaching one level. Afl-fuzz obviously does not know how to advance from here without destroying the match of the first level, I guess.

**Comment by andreafioraldi** [comment]
I tried also to disable trimming. In only one execution over 10 circa the fuzzer bypassed two checks.

**Comment by andreafioraldi** [comment]
```Afl-fuzz obviously does not know how to advance from here without destroying the match of the first level, I guess```
I don't think, this is true with the ASCII input from scanf but I'm using the version that reads raw bytes from stdin with read().

**Comment by vanhauser-thc** [comment]
what is the status here? Isnt this done?

**Comment by andreafioraldi** [comment]
yes it is
