### ISSUE TITLE
Proposition: add radamsa to list of mutators

### ISSUE THREAD

**Issue by hexcoder-** [vanhauser-thc/AFLplusplus#72]
Since radamsa now exists as a ([shared library](https://gitlab.com/akihe/radamsa/tree/develop)), we might want to add it.

It could be called like this:
`n = radamsa((uint8_t *) input, len, (uint8_t *) output, BUFSIZE, seed);`

**Comment by vanhauser-thc** [comment]
that would be a very good addition.

question would be though how often to call this on a queue_entry. maybe something like (input_len >> 4) + 1 or something like that ...

and command line option -R :)

**Comment by andreafioraldi** [comment]
+1 for the command line option, by default only the AFL mutations must be enabled.

**Comment by hexcoder-** [comment]
Thanks, so someone could implement it, hint hint ;-).

**Comment by andreafioraldi** [comment]
I will start it in the https://github.com/vanhauser-thc/AFLplusplus/tree/radamsa branch

**Comment by andreafioraldi** [comment]
The compilation of libradamsa is a bit too resource expensive and long ...
We should include the pre-translated file to avoid to download the ol compiler.

**Comment by vanhauser-thc** [comment]
your system is faster than mine ;)

```
$ time cc -O3 -I c -o lib/libradamsa.a -c c/libradamsa.c
real  3m3,785s
user 3m3,127s
sys   0m0,644s
```

I still think its a good thing to have. although with that compile time it needs to be optional
maybe a libmutator function? that would be the easiest way.

**Comment by andreafioraldi** [comment]
1m is too much, we should make it optional and load the shared library with dlopen when -R is specified.

**Comment by andreafioraldi** [comment]
I'm testing some configuration for radamsa.
If it is added in the stacked mutations in havoc it makes the fuzzer too slow.
If runned a single time in the havoc cycle but not stacked with other mutations is reasonable.
Each havoc cycle ATM I invoke radamsa instead of the stacked mutations when `UR(16) == 0`.
With this last configuration, when fuzzing tcpdump under qemu, the speed is ~1000 exec/s with radamsa vs. ~1200 w/o radamsa. The map density seems to be better with radamsa (6.92% vs 6.54% in 1.30m but can be only luck).

**Comment by andreafioraldi** [comment]
I'm using compcov qemu level 2 and now radamsa replace havoc when UR(24) == 0 (the speed increases a bit). Seems to perform worst than AFL++ in terms of speed (876 vs 994), BB coverage  (2230 vs 2540) and edge coverage (3190 vs 3670) after ~3min.

**Comment by andreafioraldi** [comment]
Basic Block coverage in 30 min of fuzzin tcpdump in QEMU mode with compcov level 2.
red line = with radamsa (1/24 of probability to replace an havoc cycle), green = normal AFL++

![pp_bb](https://user-images.githubusercontent.com/16168186/66592749-f2f04d80-eb95-11e9-987e-bdd88f7c867e.png)

**Comment by andreafioraldi** [comment]
Basic Block coverage in 30 min of fuzzing readelf in QEMU mode with compcov level 2.
![rad_bb](https://user-images.githubusercontent.com/16168186/66595014-685e1d00-eb9a-11e9-8856-ad379e487f10.png)

This feature seems to shitty for me. Maybe you can implement a better solution, try to play with the RADAMSA_CHANCE define in fuzz_one and with the max_len (maybe try just max_len = temp_len * 100)

**Comment by andreafioraldi** [comment]
![rad2_bb](https://user-images.githubusercontent.com/16168186/66598008-6303d100-eba0-11e9-86fb-2abae99a6075.png)

Same stuffs on tcpdump when I increased max_size. For me we can drop this.

**Comment by andreafioraldi** [comment]
RedQueen adds radamsa to kAFL and, in fact, in the data reported in the evaluation in the paper this stage finds only a few new interesting inputs and requires a lot of time.

**Comment by hexcoder-** [comment]
Ok, thanks for your evaluation!

**Comment by andreafioraldi** [comment]
I think that the point is that radamsa has a LISP vm inside and is written in LISP.
Too slow compared to us.

**Comment by hexcoder-** [comment]
This would explain the long compilation time also.

**Comment by vanhauser-thc** [comment]
IMHO slow/fast is not an important factor.

yes, radamsa is super slow because of lisp etc.

however the question is if it can add mutations that are helpful and would otherwise not be used. (so increase coverage and other potential crash cases)

IMHO havoc is of course better. faster and more bb coverage. Aren't bitflip and havoc the most successful mechanisms in the mutator? I think they are.

So maybe radamsa would help once the "easy" coverage stuff has been found. If I look at radamsa generated stuff, its data that would not be generated by havor or bitflip (and others) as easily. so my guess is that in later stages radamsa very likely will add interesting testcases, also reducing the speed.

Thats a theory of course, but I think its very likely.

so what could be the better integration? for example we could configure it so that after the first cycle it is performed it is added as the final mutation.

How to test the theory that radamsa is helping: one small valid input file only (e.g. tiff for libtiff), and running it though for one cycle (AFL_BENCH_JUST_ONE=1), and then comparing the coverage (and not the runtime or exec/s).

I will test this for libtiff and unrar.
@andreafioraldi: do I have to configure anything for compiling in the radamsa branch to have it? Anything on the command line I have to specify?

**Comment by andreafioraldi** [comment]
```so what could be the better integration? for example we could configure it so that after the first cycle it is performed it is added as the final mutation.```
I will test it

**Comment by andreafioraldi** [comment]
Now the radamsa mutation is performed if ```use_radamsa && queue_cycle > 1 && UR(RADAMSA_CHANCE) == 0```

**Comment by vanhauser-thc** [comment]
I did some tests over the weekend however the outcome made no sense (less path coverage by the same test cases plus more test cases ;) ) ... will try again this week ;)

**Comment by floyd-fuh** [comment]
What about libxml?

It would be good to have a list of diverse libraries that are used to benchmark AFL++. It is close to impossible to not bias performance optimization towards the targets used for benchmarking. And again automating it would be good, so I like the new test folder with the benchmarking!

Maybe it would be good to have radamsa even if it would be better only for a very specific kind of target. Of course it would be good to find at least one such target. On the other hand, if radamsa takes such a long time to compile, it is better to be optional.

**Comment by vanhauser-thc** [comment]
OK I am happy with my changes to @andreafioraldi radamsa implementation ... it works different now.

To run Radamsa with the normal mutators add -R on the command line. it will run *after* havoc.
To only run Radamsa, use -RR.

Radamsa is slow but has nice mutations where many of these afl would not produce so the addition is valuable. 

still a specific custom mutator, e.g. for XML is much better to fuzz XML.

@andreafioraldi @floyd-fuh @hexcoder-  - please have a look and test.
https://github.com/vanhauser-thc/AFLplusplus/tree/radamsa

Andrea, I hope its OK that I switched out your implementation. the way I did it we can see what radamsa actually adds to it because it runs now after havoc.

**Comment by vanhauser-thc** [comment]
Here is an example.

the Radamsa mutator is circled red and you can see it found new paths, after havoc ran, and the path:number_of_mutations relations is similar.

and that is on a binary image format. on XML etc. this should be even better.

![Screenshot from 2019-10-24 17-21-25](https://user-images.githubusercontent.com/7396244/67500536-1d0c3a00-f683-11e9-828b-275d975b9b8b.png)

**Comment by andreafioraldi** [comment]
I will add a dlopen based mechanism for that, the build time is too high for a feature that is not optimal al all the targets.
Regards the status screen, the havoc line hass too many entries and we should add a line for radamsa+custom.

**Comment by vanhauser-thc** [comment]
yeah the dlopen could be beneficial. but when people do source-only or binary-only or distrib we have to build it anyway. for a "make" only it would be faster.

I dont think we will need a new line. usually people will either run python OR radamsa OR custom. its an unlikely people run them all together as this makes no sense. and if in that unlikely case the line clashes - so be it. would be my opinion. but if you want to change it, go for it.

**Comment by andreafioraldi** [comment]
> people run them all together as this makes no sense

We can left that line for the moment, but if In the future we will generalize MOpt for all of these mutations it will make sense.
For me has sense to run havoc,splice,custom and radamsa all together if there is MOpt enabled that can later give less priority to such mutations that are less effective.

**Comment by vanhauser-thc** [comment]
btw I created an issue at radamsa -> https://gitlab.com/akihe/radamsa/issues/66

**Comment by vanhauser-thc** [comment]
so ... -O3 makes it faster than -O2, changed that in the branch

also gcc9 is much better than gcc8 is much better than clang8. 

also gcc9 compiles it in 1:30 instead of 3:00 like gcc8.

**Comment by vanhauser-thc** [comment]
its in master now, so we can close this :)
